USE KODILLA_COURSE;
DROP TABLE IF EXISTS STATS;
DROP VIEW IF EXISTS BESTSELLERS_COUNT;
DROP EVENT IF EXISTS UPDATE_BESTSELLERS;


CREATE TABLE STATS (
	STAT_ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	STAT VARCHAR(20) NOT NULL,
	STAT_DATE DATETIME NOT NULL,
	VALUE INT(11) NOT NULL
);

COMMIT;

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS
FROM BOOKS 
WHERE BESTSELLER = 1;

COMMIT;

SELECT * FROM BESTSELLERS_COUNT;

COMMIT;

INSERT INTO STATS (STAT_DATE, STAT, VALUE) 
VALUES (CURRENT_TIMESTAMP, "BESTSELLERS", (SELECT * FROM BESTSELLERS_COUNT));

DELIMITER &&

CREATE EVENT UPDATE_BESTSELLERS
	ON SCHEDULE EVERY 1 MINUTE
DO 
BEGIN
	CALL UpdateBestsellers();
	INSERT INTO STATS (STAT_DATE, STAT, VALUE) 
		VALUES (CURRENT_TIMESTAMP, "BESTSELLERS", (SELECT * FROM BESTSELLERS_COUNT));
END&&

DELIMITER ;

SELECT * FROM STATS;
