EXPLAIN SELECT COUNT(*)
FROM READERS
WHERE FIRSTNAME = "John";

CREATE INDEX TITLE_FIND ON BOOKS (TITLE);

CREATE INDEX FIRSTNAME_FIND ON READERS (FIRSTNAME);

CREATE INDEX LASTNAME_FIND ON READERS (LASTNAME);

EXPLAIN SELECT COUNT(*)
FROM READERS
WHERE FIRSTNAME = "John";
